### ISSUE TITLE
Outdated deb 

### ISSUE THREAD

**Issue by Justinzobel** [donadigo/wingpanel-indicator-namarupa#10]
Deb in releases is outdated, elementary wants to over-ride it during update.

**Comment by lainsce** [comment]
That's due to how they dropped this functionality of having a system tray.

I recommend using apt to hold it on this version.

**Comment by Justinzobel** [comment]
Not possible to patch a newer version?

**Comment by lainsce** [comment]
Yep, not possible. Newer versions would require a massive patch.
